name: Ngày cập nhật

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '_includes/updated.html'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Thiết lập Python '3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cài đặt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cập nhật Bảng xếp hạng
        run: |
          python3 python/update_time.py
      - name: Cam kết & Đẩy tệp
        run: |
          git config --local user.email "vietdinh856@gmail.com"
          git config --local user.name "Thi-Vua-Lay-Tot"
          git add -A
          git commit -m "Update"
          git push --force
